services:
  - type: worker
    name: telegram-minsk-bot
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHON_VERSION
        value: 3.11.11
    plan: free
